const Popular = () => {
  return (
    <section className="container">
      <h2
        className="flex text-3xl font-normal bg-gradient-to-r from-[#494949] to-[#313131] bg-clip-text text-transparent
        hover:bg-gradient-to-r  hover:from-[#494949] hover:to-[#313131] hover:bg-clip-text hover:text-transparent"
      >
        Popular
      </h2>
    </section>
  );
};

export default Popular;
